# Dockerfile.gui
FROM python:3.12-slim

WORKDIR /app

# install runtime deps + tkinter and X11 libs
# Dockerfile.gui (snippet)
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    python3-tk \
    x11-utils \
    tcl8.6 tk8.6 \
    xauth \
    libfontconfig1 \
    libx11-6 \
    libxext6 \
    xclip \
    xsel \
    && rm -rf /var/lib/apt/lists/*


COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENTRYPOINT ["python3", "ui_tk.py"]
